### PR TITLE
Add homebrew's current version of libuv

### PR DESCRIPTION
**Pull request by defmacro-jam**

### CODE REVIEW

**Comment by defmacro-jam** [comment]
I wasn't sure if you wanted to keep the old version -- but anybody who has done a `brew update` will have version 1.8.0 now.

**Comment by orthecreedence** [comment]
Thanks!

**Comment by defmacro-jam** [comment]
Hey,

I just realized that you’re the turtl guy — and because I have been kicking around the idea of making an ECL plugin for node, you’re the obvious person to talk to.

It looks to me like it’d be possible to add the whole of ECL as a node plugin — and that ECL would be able to reach in and gain access to most anything in node-world.  You see, I was thinking ECL + electron would be an amazing way to package desktop apps.

But you abandoned a similar project so I’m clearly missing something important.

Can you offer any warnings, tips, or other advice?

-michael

**Comment by orthecreedence** [comment]
Well, the project was a result of wanting a common platform on different devices that offered native speeds. At the time I build turtl/core, it made sense to me to do this in ECL because javascript still had a lot of growing to do before it could actually support Turtl (specifically thinking about a webview-based mobile app here). Nowadays with things like Crosswalk, being able to standardize the codebase isn't that important since pretty much all of Turtl runs on the same version of chrome pre-packaged with each build.

In other words, it became much more maintainable to use Chrome as a platform for hosting Turtl's business logic over ECL.

That said, I  managed to get ECL *successfully* embedded in both node-webkit (now NWJS) and Firefox's app platform as well. It has been a while since I did this, but I [wrote a series on this](http://turtlapp.tumblr.com/post/83184613020/embedding-lisp-in-node-webkit-part-1) which might help, and I can *try* to answer any questions you may have.

What I will say is that you'll need a Node module (native) that sets up messaging (I used nanomsg and loved it) between node and your embedded ECL instance and get them talking from there. 

Basically I had node load in the ECL shared lib, run a command to set up messaging on both sides, and then start passing messages back and forth from there to share data between each other. I just realized I never posted the source for the node module, so check out the desktop branch here: https://github.com/turtl/desktop/tree/turtl-core for clues. This is based off an OLD node version and uses NaN as a compatibility layer (definitely recommend use NaN) but should give you some hints. Keep in mind all the code is GPL, so you may want to rewrite the bits you use if that's an issue. Also I *think* I may have written my own messaging system here before I realized I could just use nanomsg (oops) but it's possible I converted it since (haven't looked at it in a while).

So my advice is: go for it. I did it. It was successful. I just couldn't justify re-writing huge portions of the app in lisp when it already worked in Chrome and Chrome suddenly became available on the platforms I was targeting. It would be so awesome to have a CL embedded in a modern web platform, and if you managed to get this packaged in a nice way AND get it on mobile it would be really incredible. Let me know if there's any questions I can answer. 

Good luck!

**Comment by defmacro-jam** [comment]
Thank you!

There’s a lot there I  had not considered.

So glad you documented your experience with it — now I just have to learn enough C++ to understand the NaN, Node, and possibly V8 documentation and examples.

-Michael

**Pull request merged**
